###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

###
# MongoDB
###
mongo:
  host: "localhost"
  port: 27017
  db: "mainflux"

###
# InfluxDB
###
influx:
  host: "localhost"
  port: 8086
  db: "mainflux"

###
# NATS
###
nats:
  host: "localhost"
  port: 4222
